# Generated by Django 4.1.7 on 2023-08-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('cnic', models.CharField(max_length=13)),
                ('address', models.TextField()),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
